pipeline {
    agent { label 'master'}
    stages {
      stage("Clean workspace"){
                steps {
                    cleanWs()
                }
            }
     stage("Pull changes from git"){
               steps{
                    git 'https://github.com/tdworowy/SeleniumExample.git'
                }
            }
      stage('Run Tests')
        {
             steps{
                    dir('java') {
                        //bat 'mvn clean test'
                         bat 'gradlew build'
                    }
                }
          }
         }
      post {
        always {
          dir('java') {
              //archiveArtifacts "target\\surefire-reports\\*\\*"
              archiveArtifacts "C:\\Users\\tdworowy\\Documents\\Selenium_traning\\Selenium_testing\\java\\build\\reports\\tests\\test\\*\\*"
              archiveArtifacts "TestLogs\\*\\*"
              archiveArtifacts "allure-results\\*"
              allure includeProperties: false, jdk: '', results: [[path: 'allure-results']]
          }
        }
      }
}